<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 3.0 License

Name       : Accumen
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20120712

Modified by VitalySwipe
-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<title>ОЛОЛОША TEAM</title>
	<link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css" />
	<link href="http://fonts.googleapis.com/css?family=Kreon" rel="stylesheet" type="text/css" />
	
	<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div id="wrapper">
	<?php echo $this->getChildHtml('header') ?>
	<div id="page">
		<?php echo $this->getChildHtml('sidebar') ?>
		<div id="content">
			<div class="box">
				<?php echo $this->getChildHtml('content') ?>
			</div>
			<br class="clearfix" />
		</div>
		<br class="clearfix" />
	</div>
    <?php echo $this->getChildHtml('page-bottom') ?>
    <br class="clearfix" />
</div>
<?php echo $this->getChildHtml('footer') ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>